name: Release - Build + Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Deploy - Release
      uses: alexr03/publish-nuget@master
      with:
        PROJECT_FILE_PATH: TCAdminApiSharp/TCAdminApiSharp.csproj
        NUGET_KEY: ${{secrets.ALEX_NUGET_API_KEY}}
        VERSION_REGEX: ^\s*<AssemblyVersion>(.*)<\/AssemblyVersion>\s*$
        TAG_VERSION: release-v*-${{steps.datetime.outputs.date}}-${{github.run_number}}