name: Dev - Build + Deploy

on:
  push:
    branches: [ dev-*, dev/**, develop, develop/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build Nuget Packages
      run: "mkdir build && dotnet pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source -o build -p:VersionSuffix='nightly' -p:BuildNumber=0$((${{ github.run_number }} ))"

    - name: Publish Nuget Packages
      run: "dotnet nuget push \"build/*\" -k ${{ secrets.ALEX_NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json"

    - name: "Upload Nuget Packages To Github Actions"
      uses: actions/upload-artifact@v3
      with:
        name: PR Nuget Packages
        path: build/*